name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java (specify Java version)
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Alternative: 'zulu' or 'adopt'
        java-version: '17'     # Use Java 17 or another version compatible with your project

    # Step 3: Cache Gradle dependencies (optional but speeds up builds)
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Step 4: Build the project using Gradle
    - name: Build with Gradle
      run: ./gradlew build
